# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f994655da25834124a11b26566df4c7c96653983237ca8b58e7abe82acaaa815ea94cfe5f361d02af5aa2f3432ad31b32096845c4c7053e3351bff7fe0774e

test:
  secret_key_base: eeee831dbe0525e085800db9a7cfb8eba2007ed7931aa64a9860b85b801647ce07d4e54d6207114132c1101332a2b825b86df0c9b54b6c2c9109567df7aa1793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
